name: BEZZTRAINING
favicon: null
layout_spectrum: 0.3375380088109523
typography_spectrum: 0.845543327042833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: vqe876229/@
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#154453'
    - '#ffffff'
    - '#688088'
    - '#3e5d68'
    - '#aeb8bb'
  brandStrength: 0.75
  lightness: 0.5323293260298669
  saturation: 0.625
  rhythmicContrast: 0.3774723573587835
purpose: []
